version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consultorio
      MYSQL_USER: pruebas
      MYSQL_PASSWORD: pruebas
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      RedDistri:
        ipv4_address: 172.80.0.2
            
  backServices:
    container_name: "back-end"
    restart: always
    build: 
        context: JavaSpring/Psychologi2
        dockerfile: Dockerfile
    image: back-services.jar:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/consultorio
      SPRING_DATASOURCE_USERNAME: pruebas
      SPRING_DATASOURCE_PASSWORD: pruebas

    networks:
      RedDistri:
        ipv4_address: 172.80.0.3

  frontPsy:
    container_name: "paginaPS"
    build:
        context: PaginaWeb/webps
        dockerfile: Dockerfile
    image: pagina
    restart: always
    ports:
      - 3000:3000
    networks:
      RedDistri:
        ipv4_address: 172.80.0.4

networks:
  RedDistri:
    ipam:
      config:
        - subnet: 172.80.0.0/24
volumes:
  mysql_data:
